wifi_ssid: "SUA_REDE_2G4"
wifi_password: "SUA_SENHA"

# No ESPHome Dashboard: Settings -> API Encryption -> Generate key
api_encryption_key: "base64:COLE_SUA_CHAVE_AQUI"

ota_password: "SUA_SENHA_OTA"

# AP fallback (opcional)
ap_password: "12345678"

